#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PRemote.Client.Android.Resource", IsApplication=true)]

namespace PRemote.Client.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int btn_Picture = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int btn_Vocal = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int img_State = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int spr_Aperture = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int spr_ISO = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int spr_Shutter = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int txt_Aperture = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int txt_ISO = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int txt_Shutter = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int txt_State = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int state_Loaded = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int state_Loading = 2130903041;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int txt_base = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
