#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PRemote.Client.Android.Resource", IsApplication=true)]

namespace PRemote.Client.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f030000
			public const int arr_Empty = 2130903040;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int btn_Picture = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int btn_Vocal = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int img_State = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int spr_Aperture = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int spr_ISO = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int spr_Shutter = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int txt_Aperture = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int txt_ISO = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int txt_Shutter = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int txt_State = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int state_Loaded = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int state_Loading = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int txt_base = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
